//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pcompany_task.Data_Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Pcompany_taskEntities : DbContext
    {
        public Pcompany_taskEntities()
            : base("name=Pcompany_taskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product_table> Product_table { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
    
        public virtual ObjectResult<sp_category_report_Result> sp_category_report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_category_report_Result>("sp_category_report");
        }
    
        public virtual ObjectResult<sp_product_report_Result> sp_product_report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_product_report_Result>("sp_product_report");
        }
    }
}
