//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pcompany_task.Data_Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.ModelBinding;

    public partial class Product_table
    {

        public int Product_id { get; set; }
        
        public Nullable<int> Category_id { get; set; }
        [Required (ErrorMessage ="please enter product name")]
        public string Product_name { get; set; }
        [Required(ErrorMessage = "please enter product price")]
        public Nullable<decimal> Price { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
